name: swift_composer
description: Extensible Object Manager with no boilerplate code using source_gen
version: 0.9.1
homepage: https://github.com/coffee-software/swift_composer
environment:
  sdk: ^3.9.0
dependencies:
  build: ^4.0.2
  build_config: ^1.1.1
  yaml: ^3.1.2
  source_gen: ^4.0.2
  path: ^1.9.0
  analyzer: ^8.4.1
dev_dependencies:
  lints: ^6.0.0
  test: any
  build_runner: any
